# Generated by Django 4.1.3 on 2022-12-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_category_created_at_category_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
