# Generated by Django 4.1.3 on 2022-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_product_quantity_product_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.FloatField(
                default=1,
                help_text="Give the quantity of the product. Example, 1 kg, 2 litres, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("LT", "Litre"),
                    ("ML", "Millilitre"),
                    ("KG", "Kilogram"),
                    ("G", "Gram"),
                    ("NOS", "Number"),
                    ("PK", "Pack"),
                    ("RL", "Roll"),
                ],
                default="nos",
                help_text="Enter unit to measure the quantity. Example, 1kg, 2litre. Here, kg and litre are the units",
                max_length=100,
            ),
        ),
    ]
