# Generated by Django 4.1.3 on 2022-12-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_product_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("LT", "lt"),
                    ("ML", "ml"),
                    ("KG", "kg"),
                    ("G", "g"),
                    ("NOS", "nos"),
                    ("PK", "pack"),
                    ("RL", "roll"),
                ],
                default="nos",
                help_text="Enter unit to measure the quantity. Example, 1kg, 2litre. Here, kg and litre are the units",
                max_length=100,
            ),
        ),
    ]
