# Generated by Django 4.1.3 on 2022-12-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0004_product_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, default="New Purchase", max_length=200, null=True
                    ),
                ),
                ("purchased_at", models.DateTimeField()),
                ("cost", models.FloatField(blank=True, default=0.0, null=True)),
                ("comments", models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("lt", "litre"),
                            ("kg", "kgs"),
                            ("g", "g"),
                            ("nos", "nos"),
                            ("pack", "pack"),
                            ("roll", "roll"),
                        ],
                        default="nos",
                        max_length=100,
                    ),
                ),
                ("cost", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.purchase",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="purchase",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="purchase.store"
            ),
        ),
    ]
