# Generated by Django 4.1.3 on 2022-12-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_alter_purchaseitem_unit"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchaseitem", name="unit",),
        migrations.AlterField(
            model_name="purchaseitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
